### PR TITLE
The big merge

### PR DESCRIPTION
**Pull request by Duzos**
a lot of changes
many, many bad
and a couple of okay things
just really bad code things fixing bugs we've found 
i wasnt planning on this code to actually go this far because i was coding on the expectation theo would redo everything which he kinda has in his pull request
mostly just going to be annoying fixing the things that will come with this merge
but we NEED to do this bro we need to have everyone and everything on the main branch
its also currently bugged! so thats nice.
going to make this a draft for now

### CODE REVIEW

**Comment by Suff99** [comment]
CTRL + A
DEL key 
????
Profit 

I jest

**Comment by Suff99** [comment]
loving all the emails I get at midnight, its like a daily update

**Comment by Duzos** [comment]
omg im so sorry i forgot that these get sent here
i was worried about spamming your emails too so i was tryna avoid doing stuff on the issues/pull requests pages 😭 
how do i disable ur email spam

**Comment by Duzos** [comment]
loqor made a seperate branch for this merging stuff, so this can b closed

**Comment by Suff99** [comment]
oh no its something i need to turn off myself lmao

**Comment by Duzos** [comment]
thats so stupid lol

**Pull request closed without merging**
